kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-account-bitd-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: bitd-operator
  apiGroup: rbac.authorization.k8s.io

